### ISSUE TITLE
RPC event stream & processing

### ISSUE THREAD

**Issue by SeedyROM** [SeedyROM/croncat-rs#2]
## Tasks:

- [x] Stream blocks from WS RPC 
- [ ] **(Processing)** Process blocks and react accordingly to cron contracts details
- [ ] **(Sanity)** Attempt task locally before on-chain execution
- [ ] ~**(Replay)** Handle historical block range WS RPC calls~

## Notes:
*nil*

**Comment by TrevorJTClarke** [comment]
@SeedyROM I dont think replay is needed. Appreciate the thought tho.
I am also unsure if the `sanity` step is possible. If so, EPIC, otherwise skip it
